### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by saveriob** [tuhiproject/tuhi#71] opened 2018-02-06 11:29 UTC
After installing Tuhi, I cannot run the daemon.
Am I doing anything wrong? How can I help to debug?
Thanks!

```
saverio@topc:~/Downloads/tuhi$ tuhi
Traceback (most recent call last):
  File "/usr/local/bin/tuhi", line 9, in <module>
    load_entry_point('tuhi==0.1', 'console_scripts', 'tuhi')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 954, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 896, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1139, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1115, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1096, in _legacy_get_spec
  File "<frozen importlib._bootstrap>", line 444, in spec_from_loader
  File "<frozen importlib._bootstrap_external>", line 533, in spec_from_file_location
  File "/usr/local/lib/python3.5/dist-packages/tuhi-0.1-py3.5.egg/tuhi/base.py", line 106
    logger.debug(f'{self.address}: loaded {len(drawings)} drawings from disk')
                                                                            ^
SyntaxError: invalid syntax
```

**Comment by saveriob** [comment] 2018-02-06 11:52
I apologize for posting without investigating before. The issue seems due to the requirement for python 3.6.
I now installed python 3.6 (which is not shipped with my Ubuntu 16.10), and I get another error:
```
Traceback (most recent call last):
  File "tuhi.py", line 14, in <module>
    import tuhi.base
  File "/home/saverio/Downloads/tuhi/tuhi/base.py", line 19, in <module>
    from gi.repository import GObject, GLib
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 42, in <module>
    from . import _gi
ImportError: cannot import name '_gi'
```

**Comment by bentiss** [comment] 2018-02-06 12:29
Yep, the first issue is Python 3.6 missing.

For the second bit, you seem to have pygobject compiled with python 3.5 while trying to use python 3.6. Please make sure all of your packages are updated and pygobject is correctly installed with the 3.6 version.

**Comment by saveriob** [comment] 2018-02-06 17:13
Ok, that part seems OK now, I got all the packages installed for the right version.
However, I get a Segmentation fault (core dumped) error now (see below)
As installing python 3.6 and the corresponding packages in ubuntu 16.04 is a bit of a mess, I am not sure you should waste your time with this issue, unless you want me to provide more info.
I will update soon to a distribution where python 3.6 is natively included, and test again.
```
/home/saverio/Downloads/tuhi/tuhi/dbusserver.py:109: TypeError: Passing arguments to gi.types.Boxed.__init__() is deprecated. All arguments passed will be ignored.
  builder = GLib.VariantBuilder(GLib.VariantType('a{sv}'))
/home/saverio/Downloads/tuhi/tuhi/dbusserver.py:113: Warning: g_variant_builder_add_value: assertion 'is_valid_builder (builder)' failed
  builder.add_value(de)
/home/saverio/Downloads/tuhi/tuhi/dbusserver.py:114: Warning: g_variant_builder_end: assertion 'is_valid_builder (builder)' failed
  properties = builder.end()
/home/saverio/Downloads/tuhi/tuhi/dbusserver.py:115: TypeError: Passing arguments to gi.types.Boxed.__init__() is deprecated. All arguments passed will be ignored.
  inval_props = GLib.VariantBuilder(GLib.VariantType('as'))
/home/saverio/Downloads/tuhi/tuhi/dbusserver.py:116: Warning: g_variant_builder_end: assertion 'is_valid_builder (builder)' failed
  inval_props = inval_props.end()
/usr/local/lib/python3.6/dist-packages/gi/overrides/GLib.py:250: Warning: g_variant_ref_sink: assertion 'value != NULL' failed
  return GLib.Variant.new_tuple(elements)
Segmentation fault (core dumped) 
```

**Comment by bentiss** [comment] 2018-02-06 17:17
Well, it's worth investigating a bit. The software is still not entirely hardened, so there might be some bugs here and there.

Could you provide (if you still can) a full log of when you run `tuhi.py` with `-v`? We might be able to understand where the issue lies or reproduce it.

Also, which device do you have?

**Comment by whot** [comment] 2018-02-06 23:45
This code is effectively standalone, you should be able to lift it into a `test.py` and then replace the values with random values of the same type. If it still complains/crashes as part of such a test script, then the isssue is definitely in python/gi, not in Tuhi.

**Comment by bentiss** [comment] 2018-02-07 08:36
This realy looks like a pygobject mess, as it seems to be using an outdated Builder. In Fedora or in the flatpak that uses the git tree, there is no such warning, so I think it's not our fault.

As @whot said, the simple following `test.py` should also raise the segfault (if not, then there is an issue in our code):
```python
#!/bin/env python3

from gi.repository import GLib

test_dict = {
  'foo': GLib.Variant.new_string('bar'),
}

builder = GLib.VariantBuilder(GLib.VariantType('a{sv}'))
for name, value in test_dict.items():
    de = GLib.Variant.new_dict_entry(GLib.Variant.new_string(name),
                                     GLib.Variant.new_variant(value))
    builder.add_value(de)
properties = builder.end()
inval_props = GLib.VariantBuilder(GLib.VariantType('as'))
inval_props = inval_props.end()

print('test OK')
```

If segfault there is, please close this bug and maybe raise an issue with your distribution (or just don't bother and switch to a distribution with native python 3.6).

One other solution could be to use flatpak to build the app, as it's more controlled. We still haven't pushed the builds onto flathub, but that's something we will eventually do.

**Comment by saveriob** [comment] 2018-02-07 08:56
Not a segfault, but still...
```
saverio@topc:~/Downloads$ python3.6 test.py 
test.py:9: TypeError: Passing arguments to gi.types.Boxed.__init__() is deprecated. All arguments passed will be ignored.
  builder = GLib.VariantBuilder(GLib.VariantType('a{sv}'))
test.py:13: Warning: g_variant_builder_add_value: assertion 'is_valid_builder (builder)' failed
  builder.add_value(de)
test.py:14: Warning: g_variant_builder_end: assertion 'is_valid_builder (builder)' failed
  properties = builder.end()
test.py:15: TypeError: Passing arguments to gi.types.Boxed.__init__() is deprecated. All arguments passed will be ignored.
  inval_props = GLib.VariantBuilder(GLib.VariantType('as'))
test.py:16: Warning: g_variant_builder_end: assertion 'is_valid_builder (builder)' failed
  inval_props = inval_props.end()
test OK
```
It seems that the issue is not in Tuhi, doesn't it? Should I close this?

**Comment by bentiss** [comment] 2018-02-07 08:58
Thanks for the quick test

> It seems that the issue is not in Tuhi, doesn't it?

Yes, it's in your pygobject port. It seems to behave fine here, but I suspect that when we pass those incomplete objects to dbus, the underlying glib/dbus library segfaults.

>  Should I close this?

I'll do it, thanks for the quick feedbacks

**Closed as completed by bentiss** 2018-02-07 08:58 UTC
Labels: needinfo - reporter
