### ISSUE TITLE
Live mode

### ISSUE THREAD

**Issue by bentiss** [tuhiproject/tuhi#43] opened 2018-01-29 12:44 UTC
The Slate has a "live mode" feature which allows to use the tablet like any other Linux tablet input device.

We already internally discussed this internally in the project, and here are some of the results:
- the live mode is handled through the same combination of Nordic and Wacom Gatt endpoint.
- TUHI should be able to switch the device to live mode and parse the incoming data (to have only one point where we speak the ink protocol)
- TUHI can not export an evdev input device directly, because it runs as a user session daemon
- we could think about having fd passing and having a client (as root) opening the uinput node and forwarding this to us, or even just handling the evdev event injections in tuhi, not the input creation
- we could also think at forcing everybody to use dbus API to retrieve the events (so a client can create an input node if it wants, but inkscape could benefit from a special plugin)
- it is definitively urgent to wait until we have a use case

The last point is the most important one actually

**Comment by lukyluket** [comment] 2018-01-31 22:34
What do you mean by a use case?
I would actually love to be able to use the slate as a normal input device on linux.

**Comment by bentiss** [comment] 2018-02-01 08:43
The problem we have, and why we need a use case is that tuhi, the daemon, runs as a session daemon. So it doesn't have the privileges to create an input node.

And by use case, we mean what are people expecting for it: a regular input node as a classic wacom tablet or a 'virtual' input handled directly by a drawing application (so the input is not shared with the system). Depending of the use case, there will be more or less lag (because python and dbus), and also we need to figure out how we can articulate the tools and API to provide a correct user experience.

Based on the API we will provide, the client will have to implement one way or one other, and the consequences are not very clear at the moment.

**Comment by whot** [comment] 2018-02-02 03:06
I think the Intuos paper will answer some of the questions because by it's very design it's both traditional and paper-like. Dunno what those answers will be though :)

**Comment by lukyluket** [comment] 2018-02-02 04:12
The main reason  I would like to use the live mode is when teaching.
I actually bought the tablet for that reason but then I realized I did not
like the software and dropped it.
What I would like to do would be to project what I write on the screen via
a class projector and then also have the possibility to record a screen
cast of my lectures.
Obviously a small delay in  that scenario would be desirable but I am not
sure how big would  be th difference in the two cases you have in  mind.
I currently dropped back to use my intuos tablet for such a task but my
students complains about the lack of clarity of my handwriting and thus
think that with a paper solution for this would improve.
The obvious limitations of the paper solutions ( the cheap one based on a
slate)  are
1) lack of eraser
2) lack of right clicking
And in this sense as a pointing device it would be fairly limited....
But maybe one could think of keyboard modifiers to implement those though
it would loose one of the advantages of the slate with respect to the
intuos... The possibility of moving around during the lecture....
I guess that with a virtual device we could get plugins for say krita
inkscape xournal gimp....
Am I right?
Cheers
Luca

On 2 Feb 2018 03:06, "Peter Hutterer" <notifications@github.com> wrote:

I think the Intuos paper will answer some of the questions because by it's
very design it's both traditional and paper-like. Dunno what those answers
will be though :)

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/tuhiproject/tuhi/issues/43#issuecomment-362472532>, or mute
the thread

**Comment by whot** [comment] 2018-02-02 05:03
going through the evdev route would also mean we may have to reproduce a bunch of peculiarities that wacom does on the tablet devices. 

> I guess that with a virtual device we could get plugins for say krita inkscape xournal gimp....

no, the other way round. with a virtual (evdev) device it would just work as a normal tablet. sending events via DBus would almost certainly require plugins in those applications, limiting the tablet on the rest of the screen. But I think that wouldn't be half-bad

**Comment by bentiss** [comment] 2018-02-06 10:55
Update on this one. I have a WIP branch in #70 that allows to create a standard input device when a script is run.
@lukyluket would you mind giving it a try to see if this would match your needs?

**Comment by lukyluket** [comment] 2018-02-06 11:07
Sure give me a couple of weeks I have a deadline at work that is driving me
crazy.
Will try it soon after the 15, cheers Luca

**Comment by bentiss** [comment] 2018-02-13 21:04
FYI, the live mode support has been merged in #70. So whenever you can, feel free to test it and report any bugs you see or enhancements you want to see (there is no rush).

**Comment by lukyluket** [comment] 2018-02-13 21:06
Thanks Benjamin  I am really looking forward to test it, will let you know
soon
Cheers
Luca

**Comment by relishcolouredhat** [comment] 2018-10-01 23:16
Came here to see about using live mode with a slate as an alternative pointing device for my workstation after receiving a temporary hand injury. Now unclear if I can use slate with live mode but seems promising if I read the merge right?

**Comment by bentiss** [comment] 2018-10-03 14:23
@relishcolouredhat : You are correct. I just retested it, and the live mode works in the master branch. You need to run `tools/tuhi-live.py` as root to be able to have the new pointer created.

**Comment by gbraad** [comment] 2019-03-14 13:42
I have tried this, but no pointer is created... Perhaps I doing something wrong, but I also noticed that while the device shows connected, it actually flashes the blue LED. This is not the same as what happens when on Android.

**Comment by lukyluket** [comment] 2019-03-14 13:45
In my case the script in the tools directory kete-live.py does the job,
however I need to run it as super user

**Comment by whot** [comment] 2019-03-14 23:35
`kete-live` creates a uinput device and for that you need to be root, so that's expected.

@gbraad: most likely tuhi doesn't connect correctly to this device then. probably best to file a separate bug unless everything else works fine.

**Comment by gbraad** [comment] 2019-03-15 03:37
The larger Bamboo slate works; the issue is already filed as #117

**Comment by whot** [comment] 2019-08-27 07:06
live mode has been availble for some time, see #70. I think we can close this issue and work on the remaining issues separately.

**Closed as completed by whot** 2019-08-27 07:06 UTC
Labels: enhancement, postponed - usecase required, live mode
