### ISSUE TITLE
Architectural comments

### ISSUE THREAD

**Issue by hadess** [tuhiproject/tuhi#59] opened 2018-01-31 19:05 UTC
Good project!

I've looked through the API, and had a few comments:
- the D-Bus API seems to copy quite a bit of the bluetoothd API when it comes to pairing/unpairing/etc. Is this really needed if all the devices use the same Bluetooth LE transport? In any case, I'd move this functionality to the client, rather than expect the daemon to 
- is there any reason for the daemon not to live in the application, or at least in the Flatpak bundle? We could poke a hole through for that, or make a portal that would allow access to BLE devices with a particular GATT value. We can expect the bluetoothd API to stay stable, but the implementation talking to the devices to be refined over time, and expanded quickly. So it's better for it to live with the application (inside the Flatpak container) than in the OS (outside the Flatpak container).
- it would be nice to add the battery support directly in bluetoothd, so that UPower can pick it up when the device is connected. This is the implementation for the generic profile: https://git.kernel.org/pub/scm/bluetooth/bluez.git/tree/profiles/battery/battery.c
- I would also remove most of the duplicated metadata in the Device section, a D-Bus path in bluetoothd's D-Bus would likely give you all the metadata you'd want, including the ability to rename specific devices, and get metadata that's not available in the tuhi API **edit: filed as #60**

I can file specific issues if you agree on a path forward.

**Comment by whot** [comment] 2018-01-31 21:12
* regarding pairing: note that pairing in Tuhi has a different meaning than in Bluetooth, we just don't have a better word for it. Whether the device is paired at the Bluetooth level is irrelevant for Tuhi and the device. Same with the listening, etc. there is enough stuff in the daemon to handle this to make me weary of moving this to the client.
* We have a Flatpak issue open (#31) but we're missing Python 3.6 in the flatpaks right now. but yeah, it can be bundled with whatever needs it. The main question is whether we'll ever have a case of more than one application that wants to talk to the device - in that case we'll need a single daemon only 
* battery level: not immediately sure how to go about this but sounds like a good idea. the battery level is one of the things the serial controller sends us as part of the connection, it's not a GATT service on the device.
* metadata: good point, having the path to the bluez device would work

The last two worth filing issues for, the first one seems to be mostly a thesaurus challenge.

**Comment by bentiss** [comment] 2018-02-01 07:58
Few additions to what @whot said:
- the *pairing* is more of a reverse-pairing if you compare it to bluez. The pairing here consists in registering the host (application) with the device and setting up the clock of the device. This clearly requires a deep knowledge of the internal protocol the device speaks and is not just a proxy over the regular Bluetooth `Pair()`
- yes, we can imagine having both the daemon and the app in the same flatpak. After all, all we need is dbus communication with bluez, so it should be fairly trivial to open the required portals. Python 3.6 is an issue as there is some syntax sugar we prefer to use in 3.6 that makes the code much easier to read
- the device already exports a standard battery GATT characteristic, and it's working fine with bluetoothd. However, the amount of time we connect to the device is to the order of one or two seconds. So basically, even if upowerd shows the device, it'll will just pop up and disappear immediately. This is less than ideal, and I do not think it matters a lot to keep the battery level in upower. The device is meant to be used unconnected, so not having the battery anywhere else outside of the client of tuhi is not an issue IMO.
When used in live mode (the device can emulate a regular wacom tablet), the device will stay connected, and upower will show the meaningful information of the battery.
- metadata: should be merged shortly :)

**Comment by whot** [comment] 2018-02-01 08:13
On item 1: let's rename it to 'register' to avoid the confusion with bluetooth pairing. That's the word i've been looking for :)

**Comment by hadess** [comment] 2018-02-01 09:08
"register" or "setup" or "initialsetup" depending on whether it's regularly needed or not. Would also be nice to mention whether Bluetooth pairing is required.

It would be nice to think about how the initial setup is made, the flow of it, as well as repeat "downloads" of sketches, to see whether we can make it easier on the gnome-bluetooth/Bluetooth panel side or in the tuhi-using apps or daemon.

**Comment by whot** [comment] 2018-02-01 10:49
'register' is required once per device, but if the user registers with other hosts (e.g. inkspace) you need to re-register.

The flow itself is, in summary, hold button on tablet until it blinks, connect and start sending magic commands, press the device's button when prompted (this must be at a specific point during the exchange).

**Comment by whot** [comment] 2018-02-01 23:52
Bug for using "registering" instead of "pairing" is now #67

**Comment by hadess** [comment] 2018-02-02 02:09
> When used in live mode (the device can emulate a regular wacom tablet), the device will stay connected, and upower will show the meaningful information of the battery.

So, if this already works, you can close the bug now, all my comments were handled.

> The flow itself is, in summary, hold button on tablet until it blinks, connect and start sending magic commands, press the device's button when prompted (this must be at a specific point during the exchange).

No, I meant the full flow, from initial setup to false paths the user might take (such as opening the Bluetooth panel), or where they might look for related information (in the Wacom panel for example).

**Comment by whot** [comment] 2018-02-02 02:54
tbh, I think that's more in scope for the GUI app we'll eventually need that tuhi as dbus daemon.

**Comment by hadess** [comment] 2018-02-02 13:08
> tbh, I think that's more in scope for the GUI app we'll eventually need that tuhi as dbus daemon.

I think that might allow you to make better decisions about the API you want to provide for that UI. But if it's unstable, you can also learn from your trials, although you'd probably want that documented before working on the UI anyway. Up to you.

**Comment by bentiss** [comment] 2018-02-06 14:29
> >  When used in live mode (the device can emulate a regular wacom tablet), the device will stay connected, and upower will show the meaningful information of the battery.

> So, if this already works, you can close the bug now, all my comments were handled.

With PR #70, I can confirm it works (the bluetooth battery part). However, the funny thing is that the wacom.ko kernel module also tries to export a battery node, which stays at 0%. I'll chase this one down.

@hadess, are you happy with our answers regarding the GUI? If so, I'd like to close this bug.

Note that for now the flatpak we build has both the tuhi daemon and the tuhi-kete script, so you can consider the 2 of them bundled together. If we were to write the GUI (@whot had a good name for it too), we can bundle the daemon and the GUI altogether too.

**Comment by hadess** [comment] 2018-02-06 14:42
> @hadess, are you happy with our answers regarding the GUI? If so, I'd like to close this bug.

Not really, but if you prefer having the API change as the design of the UI comes along, then go for it.

**Comment by whot** [comment] 2019-08-27 07:05
> is there any reason for the daemon not to live in the application, or at least in the Flatpak bundle?

that's fixed now that we have the GUI.

Which means I think the only remaining issue was the battery but benjamin commented on that in https://github.com/tuhiproject/tuhi/issues/59#issuecomment-362187116. Which means I think we can close this issue.

**Closed as completed by whot** 2019-08-27 07:05 UTC
