### ISSUE TITLE
Location of the transfered files with flatpak version

### ISSUE THREAD

**Issue by kir0ul** [tuhiproject/tuhi#255] opened 2020-06-13 16:55 UTC
Hi,
Thanks for developing this awesome project!
I successfully installed the flatpak version and was able to transfer some files from my device to the Tuhi app on my computer. However I'm unable to find the location of the files on my computer. Would you have any idea where the flatpak version of Tuhi keeps the transferred files?

**Comment by whot** [comment] 2020-06-16 06:31
The files should show up every time you start tuhi anyway, then you can export it. isn't that the case?

https://github.com/tuhiproject/tuhi/wiki/Log-files has a list of directories and files tuhi keeps around but for normal usage (fetching from device and exporting to svg) it shouldn't be needed.

**Comment by kir0ul** [comment] 2020-07-19 18:35
Sorry for the late answer. Yes the files do show when I open the app, and I can export them as SVG. But I don't understand where they are exported. It shows my Home folder but doesn't show anything inside (see screenshot below), and I can't see the file outside of the Tuhi app. Is it related to some Flatpak sandbox?

![image](https://user-images.githubusercontent.com/6053592/87882216-a3fd0180-c9cc-11ea-80d0-1cebe809118f.png)

Also thanks to your pointer I finally found where the actual files are located: 
```
$HOME/.var/app/org.freedesktop.Tuhi/cache/tuhi/svg
```

**Comment by whot** [comment] 2020-07-20 00:38
Note the the *cache* folder is for temporary storage, those files will be regenerated all the time (e.g. if you change orientation). Don't rely on those files.

Exporting a file *should* work but there was a bug (#230) fixed on git master, myy guess is you're on 0.3. We're overdue a release, I'll try to get that out asap.

**Comment by kir0ul** [comment] 2020-07-20 15:00
Thanks :+1: 
I'm indeed on version 0.3.

**Comment by whot** [comment] 2020-07-22 00:43
[0.4 is now on flathub](https://flathub.org/apps/details/org.freedesktop.Tuhi), closing as Duplicate of #230.

**Closed as completed by whot** 2020-07-22 00:43 UTC

**Comment by kir0ul** [comment] 2020-08-02 17:47
I updated to version 0.4, but I still have the exact same problem, i.e. when I export the SVG files I can't see them outside of Tuhi.

**Comment by kir0ul** [comment] 2020-09-03 19:56
Works perfectly now with version 0.5 :tada:
Thanks!
