### ISSUE TITLE
Tuhi Live multiple screens

### ISSUE THREAD

**Issue by JustSaX** [tuhiproject/tuhi#288] opened 2022-03-05 20:55 UTC
I tried tuhi-live but I have three screens and my bamboo slate spans over all three screens. E.g. the top left corner of my slate is the same as the the top left corner of my screen that is all the way on the left. And the right bottom corner of the slate is the right bottom corner of my screen to the right. This makes everything I want to sketch with my slate very skewed.

Is it possible to resctrict tuhi-live to only one screen, or to just one program?

Thanks!

**Comment by JustSaX** [comment] 2022-03-06 06:59
I think I can answer myself even though I don't have a solution yet.

As stated in https://github.com/tuhiproject/tuhi/issues/279 it's not a problem of Tuhi but more of x11/Wayland.

Some information can be found here https://wiki.archlinux.org/title/wacom_tablet.

**Comment by whot** [comment] 2022-04-27 23:19
Closing as duplicate of #279

**Closed as completed by whot** 2022-04-27 23:19 UTC
